name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main   # Lance le workflow à chaque push sur main

permissions:
  contents: write   # ✅ Donne le droit au bot GitHub de créer/modifier gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # ou "flutter-version: '3.32.7'" si tu veux verrouiller

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
