name: Flutter - Build APKs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build_apks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Get dependencies
        run: flutter pub get

      - name: Build release APKs (split per ABI)
        run: flutter build apk --release --split-per-abi --no-shrink

      - name: Upload release APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apks
          path: build/app/outputs/flutter-apk/

      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle --release --no-shrink

      - name: Upload appbundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
